//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyData
    {
        public int IdCompanyData { get; set; }
        public string TypeOfActivity { get; set; }
        public string CompanyName { get; set; }
        public string FirstNameCompanyOwner { get; set; }
        public string LastNameCompanyOwner { get; set; }
        public Nullable<decimal> NIP { get; set; }
        public Nullable<decimal> REGON { get; set; }
        public Nullable<int> IdAdress { get; set; }
        public Nullable<int> IdCustomer { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
