//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRaport
    {
        public int IdCustomerRaport { get; set; }
        public Nullable<int> HowMuchNewUser { get; set; }
        public Nullable<int> HowLostUser { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Period { get; set; }
    }
}
