//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportExportLogs
    {
        public int IdLog { get; set; }
        public string ActionType { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> IdInvoice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
