//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItems
    {
        public int IdInvoiceItems { get; set; }
        public Nullable<int> IdInvoice { get; set; }
        public Nullable<int> IdTowar { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Towar Towar { get; set; }
    }
}
