//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int IdNotification { get; set; }
        public string Message { get; set; }
        public Nullable<int> IdCustomer { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
