//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int IdSettings { get; set; }
        public string Language { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<bool> PaymentDeadlineTrigger { get; set; }
        public Nullable<bool> NewInoviceTrigger { get; set; }
        public Nullable<bool> PymentNotMade { get; set; }
        public Nullable<int> IdCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
